name: Release
on:
  release:
    types: [published,prereleased]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Zip asset
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'sd_your.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload asset
      uses: softprops/action-gh-release@v2
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        files: sd_your.zip
