name: Release
on:
  release:
    types: [published,prereleased]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Create folder to zip
      shell: bash
      run: |
        mkdir .tmp_hidden
        mv ./* .tmp_hidden
        mv ./.htaccess .tmp_hidden
        mv .tmp_hidden sd_yourio
    - name: Zip asset
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'sd_yourio.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload asset
      uses: softprops/action-gh-release@v2
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        files: sd_yourio.zip
